# Generated by Django 5.1.3 on 2024-12-06 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Puppy', 'Puppy'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=10, verbose_name='Age')),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AF', 'Afghan Hound'), ('AP', 'Airedale Terrier'), ('AM', 'American Bulldog'), ('AB', 'American Cocker Spaniel'), ('AS', 'Australian Shepherd'), ('AU', 'Australian Terrier'), ('BE', 'Beagle'), ('BS', 'Basset Hound'), ('BL', 'Bernese Mountain Dog'), ('BO', 'Border Collie'), ('BU', 'Boxer'), ('BR', 'Brittany Spaniel'), ('CA', 'Cairn Terrier'), ('CH', 'Chihuahua'), ('CI', 'Chinese Shar-Pei'), ('CO', 'Collie'), ('CO', 'Cocker Spaniel'), ('CA', 'Cocker Spaniel'), ('DA', 'Dachshund'), ('DO', 'Doberman Pinscher'), ('EL', 'English Bulldog'), ('ES', 'English Setter'), ('EP', 'English Springer Spaniel'), ('FR', 'French Bulldog'), ('GE', 'German Shepherd'), ('GR', 'Golden Retriever'), ('GW', 'Great Dane'), ('GI', 'Great Pyrenees'), ('HUS', 'Husky'), ('IR', 'Irish Terrier'), ('JACK', 'Jack Russell Terrier'), ('KERRY', 'Kerry Blue Terrier'), ('LAB', 'Labrador Retriever'), ('MAL', 'Maltese'), ('MAL', 'Miniature Schnauzer'), ('NA', 'Newfoundland'), ('PE', 'Pembroke Welsh Corgi'), ('PO', 'Poodle'), ('POM', 'Pomeranian'), ('POM', 'Pug'), ('RAT', 'Rat Terrier'), ('RO', 'Rottweiler'), ('SH', 'Shiba Inu'), ('SHI', 'Shih Tzu'), ('SI', 'Silky Terrier'), ('SNO', 'Schnauzer'), ('SP', 'Spanish Water Dog'), ('TERR', 'Terrier'), ('TERR', 'West Highland Terrier'), ('YORK', 'Yorkshire Terrier')], max_length=50, verbose_name='Breed Name')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=10, verbose_name='Size')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='FName')),
                ('last_name', models.CharField(max_length=50, verbose_name='LName')),
                ('age', models.CharField(max_length=50, verbose_name='age')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('contact_number', models.CharField(max_length=50, verbose_name='Contact Number')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Pet Description')),
                ('medical_description', models.CharField(max_length=100, verbose_name='Medical Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to='app.age')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to='app.breed')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to='app.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_images/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Shelter Name')),
                ('contact_number', models.CharField(max_length=50, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Website Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelter', to='app.geolocation')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to='app.shelter'),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to='app.size'),
        ),
    ]
