# Generated by Django 5.1.3 on 2024-12-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ages',
            new_name='Age',
        ),
        migrations.RenameModel(
            old_name='Breeds',
            new_name='Breed',
        ),
        migrations.RenameModel(
            old_name='Genders',
            new_name='Gender',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Pets',
            new_name='Pet',
        ),
        migrations.RenameModel(
            old_name='Shelters',
            new_name='Shelter',
        ),
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
    ]
