# Generated by Django 5.1.3 on 2024-12-06 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_image_pet_image_content_type_image_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='object_id',
        ),
        migrations.AddField(
            model_name='image',
            name='pet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.pet'),
            preserve_default=False,
        ),
    ]
