# Generated by Django 5.1.3 on 2024-12-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_image_content_type_remove_image_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=50, verbose_name='Animal Name')),
            ],
        ),
    ]
