# Generated by Django 5.1.3 on 2024-12-07 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to='app.animal'),
        ),
    ]
