# Generated by Django 5.1.3 on 2024-12-08 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pet_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='animal',
        ),
        migrations.AddField(
            model_name='breed',
            name='animal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_type', to='app.animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=10, verbose_name='Animal Type'),
        ),
    ]
