# Generated by Django 5.1.3 on 2024-12-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_pet_animal_breed_animal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(choices=[('Afghan Hound', 'Afghan Hound'), ('Airedale Terrier', 'Airedale Terrier'), ('American Bulldog', 'American Bulldog'), ('American Cocker Spaniel', 'American Cocker Spaniel'), ('Australian Shepherd', 'Australian Shepherd'), ('Australian Terrier', 'Australian Terrier'), ('Beagle', 'Beagle'), ('Basset Hound', 'Basset Hound'), ('Bernese Mountain Dog', 'Bernese Mountain Dog'), ('Border Collie', 'Border Collie'), ('Boxer', 'Boxer'), ('Brittany Spaniel', 'Brittany Spaniel'), ('Cairn Terrier', 'Cairn Terrier'), ('Chihuahua', 'Chihuahua'), ('Chinese Shar-Pei', 'Chinese Shar-Pei'), ('Collie', 'Collie'), ('Cocker Spaniel', 'Cocker Spaniel'), ('Cocker Spaniel', 'Cocker Spaniel'), ('Dachshund', 'Dachshund'), ('Doberman Pinscher', 'Doberman Pinscher'), ('English Bulldog', 'English Bulldog'), ('English Setter', 'English Setter'), ('English Springer Spaniel', 'English Springer Spaniel'), ('French Bulldog', 'French Bulldog'), ('German Shepherd', 'German Shepherd'), ('Golden Retriever', 'Golden Retriever'), ('Great Dane', 'Great Dane'), ('Great Pyrenees', 'Great Pyrenees'), ('Husky', 'Husky'), ('Irish Terrier', 'Irish Terrier'), ('Jack Russell Terrier', 'Jack Russell Terrier'), ('Kerry Blue Terrier', 'Kerry Blue Terrier'), ('Labrador Retriever', 'Labrador Retriever'), ('Maltese', 'Maltese'), ('Miniature Schnauzer', 'Miniature Schnauzer'), ('Newfoundland', 'Newfoundland'), ('Pembroke Welsh Corgi', 'Pembroke Welsh Corgi'), ('Poodle', 'Poodle'), ('Pomeranian', 'Pomeranian'), ('Pug', 'Pug'), ('Rat Terrier', 'Rat Terrier'), ('Rottweiler', 'Rottweiler'), ('Shiba Inu', 'Shiba Inu'), ('Shih Tzu', 'Shih Tzu'), ('Silky Terrier', 'Silky Terrier'), ('Schnauzer', 'Schnauzer'), ('Spanish Water Dog', 'Spanish Water Dog'), ('Terrier', 'Terrier'), ('West Highland Terrier', 'West Highland Terrier'), ('Yorkshire Terrier', 'Yorkshire Terrier')], max_length=50, verbose_name='Breed Name'),
        ),
    ]
