# Generated by Django 5.1.3 on 2024-12-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_breed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=50, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=50, verbose_name='Longitude'),
        ),
    ]
