# Generated by Django 5.1.3 on 2024-12-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_geolocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='latitude',
            field=models.DecimalField(decimal_places=25, max_digits=40, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='longitude',
            field=models.DecimalField(decimal_places=25, max_digits=40, verbose_name='Longitude'),
        ),
    ]
