# Generated by Django 5.1.3 on 2024-12-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_breed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(choices=[('Domestic Shorthair', 'Domestic Shorthair'), ('Persian', 'Persian'), ('Siamese', 'Siamese'), ('Maine Coon', 'Maine Coon'), ('Bengal', 'Bengal'), ('Abyssinian', 'Abyssinian'), ('Ragdoll', 'Ragdoll'), ('British Shorthair', 'British Shorthair'), ('Sphynx', 'Sphynx'), ('Scottish Fold', 'Scottish Fold'), ('Russian Blue', 'Russian Blue'), ('Birman', 'Birman'), ('Oriental Shorthair', 'Oriental Shorthair'), ('Exotic Shorthair', 'Exotic Shorthair'), ('Turkish Angora', 'Turkish Angora'), ('Aspin', 'Aspin'), ('Shih Tzu', 'Shih Tzu'), ('Poodle', 'Poodle'), ('Chihuahua', 'Chihuahua'), ('Maltese', 'Maltese'), ('Dachshund', 'Dachshund'), ('Pomeranian', 'Pomeranian'), ('Beagle', 'Beagle'), ('Labrador Retriever', 'Labrador Retriever'), ('Pit Bull Terrier', 'Pit Bull Terrier'), ('Doberman Pinscher', 'Doberman Pinscher'), ('Boxer', 'Boxer'), ('German Shepherd', 'German Shepherd'), ('Bulldog', 'Bulldog'), ('Rottweiler', 'Rottweiler')], max_length=50, verbose_name='Breed Name'),
        ),
    ]
