# Generated by Django 5.1.3 on 2024-12-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_breed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Shelter Name'),
        ),
    ]
