# Generated by Django 5.1.3 on 2024-12-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_shelter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Pet Description'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='medical_description',
            field=models.CharField(max_length=1000, verbose_name='Medical Description'),
        ),
    ]
