# Generated by Django 5.1.3 on 2024-12-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_breed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='name',
            field=models.CharField(choices=[('Puppy | Kitten', 'Puppy | Kitten'), ('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=14, verbose_name='Age'),
        ),
    ]
