# Generated by Django 5.1.3 on 2024-12-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_age_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='name',
            field=models.CharField(choices=[('Puppy | Kitten (0 - 1 Year)', 'Puppy | Kitten (0 - 1 Year)'), ('Young (1 - 3 Years)', 'Young (1 - 3 Years)'), ('Adult (3 - 7 Years)', 'Adult (3 - 7 Years)'), ('Senior (7+ Years)', 'Senior (7+ Years)')], max_length=30, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('S (0 - 10 kg)', 'Small (0 - 10 kg)'), ('M (10 - 25 kg)', 'Medium (10 - 25 kg)'), ('L (25 - 40 kg)', 'Large (25 - 40 kg)'), ('XL (40+ kg)', 'Extra Large (40+ kg)')], max_length=15, verbose_name='Size'),
        ),
    ]
